package pqt.dss.vcr.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 20 11:44:07 PKT 2016
// ---------------------------------------------------------------------
public interface DssVisitingCardReqView extends ViewObject {
    void setNVC_wfDocumentId(oracle.jbo.domain.Number value);
}

