package pqt.dss.vcr.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 01 13:10:45 PKT 2016
// ---------------------------------------------------------------------
public interface DssVisitingCardReqHdrView extends ViewObject {
    void setNVC_wfDocumentId(oracle.jbo.domain.Number value);

    void vcrSearchUser();
}

